### ISSUE TITLE
is_cuda_available crash

### ISSUE THREAD

**Issue by chrisflesher** [NVIDIA/warp#35]
Just installed this for fun on a computer without a GPU and found a bug, maybe easy to fix?

```
>>> import warp as wp
>>> wp.is_cuda_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/warp/context.py", line 871, in is_cuda_available
    return runtime.cuda_device != None
AttributeError: 'NoneType' object has no attribute 'cuda_device'
```

**Comment by chrisflesher** [comment]
Oh, I have to call `wp.init()` first, not sure if this counts as a bug then.

**Comment by mmacklin** [comment]
Thanks, we handle this better now in 0.4.3.

Cheers,
Miles
