### ISSUE TITLE
[QUESTION] Cannot import "warp.sparse.BsrMatrix"

### ISSUE THREAD

**Issue by SangHunHan92** [NVIDIA/warp#370]
I installed warp either via the pre-built pip or by building it myself, but neither of those methods allowed me to use warp.sparse. It seems like it was missing during installation.

```
pip install warp-lang # pre-built

git clone https://github.com/NVIDIA/warp.git && cd warp # build the library
python build_lib.py
pip install -e .
```

```
>>> import warp as wp
>>> wp.autograd.jacobian
<function jacobian at 0x7f7369553940>
>>> warp.spatial_jacobian
<Function spatial_jacobian(S: array(ndim=1, dtype=<class 'warp.types.vector.<locals>.vec_t'>), joint_parents: array(ndim=1, dtype=<class 'warp.types.int32'>), joint_qd_start: array(ndim=1, dtype=<class 'warp.types.int32'>), joint_start: int32, joint_count: int32, J_start: int32, J_out: array(ndim=1, dtype=~Float))>
>>> warp.sparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'warp' has no attribute 'sparse'
>>> warp.sparse.BsrMatrix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'warp' has no attribute 'sparse'
```

As you can see from the site, warp.sparse appears to be available: 
https://nvidia.github.io/warp/modules/sparse.html#warp-sparse
How can this problem be solved?

**Comment by SangHunHan92** [comment]
It was my mistake
```
import warp.sparse as wps
bsr_matrix = wps.BsrMatrix()
```
