### ISSUE TITLE
wp.init() crash with error of  Could not find module '<..>warp.dll' (or one of its dependencies)

### ISSUE THREAD

**Issue by maria-korosteleva** [NVIDIA/warp#69]
Hi!

I've installed warp with pip: `pip install warp-lang`. After I try to execute
```
import warp as wp
wp.init()
```

I get a FileNotFoundError: 
```
Traceback (most recent call last):
  File ".\examples\example_sim_ant.py", line 26, in <module>
    wp.init()
  File "C:\Users\mariako\anaconda3\envs\warp\lib\site-packages\warp\context.py", line 2173, in init
    runtime = Runtime()
  File "C:\Users\mariako\anaconda3\envs\warp\lib\site-packages\warp\context.py", line 1050, in __init__
    self.core = warp.build.load_dll(os.path.join(bin_path, warp_lib))
  File "C:\Users\mariako\anaconda3\envs\warp\lib\site-packages\warp\build.py", line 323, in load_dll
    dll = ctypes.CDLL(dll_path, winmode=0)
  File "C:\Users\mariako\anaconda3\envs\warp\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\mariako\anaconda3\envs\warp\Lib\site-packages\warp\bin\warp.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

However, the dll file is on it's place
<img width="611" alt="Screenshot 2022-11-11 112135" src="https://user-images.githubusercontent.com/6837635/201320166-a556067c-f4c6-4fe0-8ed4-d5b2c2d6ff73.png">

I checked `warp.dll` dependencies with https://github.com/lucasg/Dependencies tool, and some entries looks suspicious

<img width="1401" alt="Screenshot 2022-11-11 112343" src="https://user-images.githubusercontent.com/6837635/201320587-b977738f-be67-450a-b129-e720e08ec332.png">

However, I'm sure what to do from here. May I ask to take a look

I'm using Windows 11, python 3.8 in conda environment

**Comment by maria-korosteleva** [comment]
@mmacklin Thank you! I would appreciate extra debugging tips

What is the ETA of the switch to static linking, if you are ok with disclosing this information, of course?

**Comment by maria-korosteleva** [comment]
The problem does not reproduce in v0.7.2 🙂
