### ISSUE TITLE
Unable to run warp exemple on Windows WLS.

### ISSUE THREAD

**Issue by rcremese** [NVIDIA/warp#81]
Hi,
I am very interested in what warp seems to do and I wanted to test it on my local desktop. 
So I tried the installation procedure mentioned in the [main page](https://github.com/NVIDIA/warp) and tried to run the tests.
I get the following output which indicate their is an error and CUDA is not recognized.
```shell
 python -m warp.tests
Warp CUDA error: Could not open libcuda.so.
Warp 0.7.2 initialized:
   CUDA not available
   Devices:
     "cpu"    | x86_64
   Kernel cache: /home/rcremese/.cache/warp/0.7.2

Skipping Torch tests due to exception: No module named 'torch'
Skipping Torch DLPack tests due to exception: No module named 'torch'
Skipping Jax DLPack tests due to exception: No module named 'jax'
test_volume_allocation_f (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_allocation_i (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_allocation_v (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_introspection (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_sample_linear_f_gradient (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_sample_linear_v_gradient (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_store (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_volume_transform_gradient (warp.tests.test_volume.register.<locals>.TestVolumes) ... ok
test_func_export_cpu (warp.tests.test_func.register.<locals>.TestFunc) ... ok
test_addition_float16 (warp.tests.test_quat.register.<locals>.TestQuat) ... ERROR

======================================================================
ERROR: test_addition_float16 (warp.tests.test_quat.register.<locals>.TestQuat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rcremese/mambaforge/envs/physic-env/lib/python3.9/site-packages/warp/tests/test_base.py", line 144, in test_func
    func(self, device, **kwargs)
  File "/home/rcremese/mambaforge/envs/physic-env/lib/python3.9/site-packages/warp/tests/test_quat.py", line 395, in test_addition
    wp.launch(kernel, dim=1, inputs=[q,v,], outputs=[r0,r1,r2,r3], device=device)
  File "/home/rcremese/mambaforge/envs/physic-env/lib/python3.9/site-packages/warp/context.py", line 2091, in launch
    success = kernel.module.load(device)
  File "/home/rcremese/mambaforge/envs/physic-env/lib/python3.9/site-packages/warp/context.py", line 863, in load
    raise RuntimeError("Failed to build CPU module because no CPU buildchain was found")
RuntimeError: Failed to build CPU module because no CPU buildchain was found

----------------------------------------------------------------------
Ran 10 tests in 0.006s

FAILED (errors=1)
```
I guess this is due to the fact that I test it on a Windows WLS2 with an Ubuntu 20.04 distro. Nevertherless, I installed the CUDA toolkit on my Windows machine as explained [here](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) and checked that CUDA is recognized in WSL (cf. below).
```shell
 nvidia-smi
Tue Mar  7 14:29:45 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 531.14       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2070 w...    On | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P5               12W /  N/A|      0MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
``` 
Therefore, I wonder where the problem might come from and if it's possible to use warp on Windows WSL. 
Thank you.

**Comment by mmacklin** [comment]
Hi @rcremese, in version `0.8.1` we fixed a number of issues with CUDA under WSL, specifically in this commit: 19c1b58f7a3b129d616d3f2519258b097936420b

I am going to close the bug, but feel free to re-open if it's not fixed for you.

Cheers,
Miles
